package pt.psoft.g1.readers.readermanagement.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "READERS_TEMP")
@Getter
@Setter
public class ReaderTemp {

    @Id
    @Column(name = "readerId")
    private String readerId;   // TEMP readerId generated by Readers

    @Column(nullable = false)
    private String userId;     // TEMP userId (will be replaced after saga)

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String email;

    protected ReaderTemp() {
        // for ORM only
    }

    public ReaderTemp(String readerId, String userId, String name, String email) {
        this.readerId = readerId;
        this.userId = userId;
        this.name = name;
        this.email = email;
    }
}
