package pt.psoft.g1.users.usermanagement.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import pt.psoft.g1.users.shared.model.Name;

@Entity
@Table(name = "T_USER_TEMP")
@Getter
@Setter
@JsonIgnoreProperties(ignoreUnknown = true)
public class UserTemp {

    @Id
    @Column(name = "USER_ID")
    private String userId;   // TEMP userId generated by Users

    @Column(nullable = false, unique = true)
    private String username;

    @Column(nullable = false)
    private String password; // already encoded or raw depending on your flow

    @Embedded
    private Name name;

    protected UserTemp() {
        // for ORM only
    }

    public UserTemp(String userId, String username, String password, Name name) {
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.name = name;
    }
}
